# Generated by Django 6.1.1 on 2026-09-26 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tiện nghi (VD: Wifi, Smart TV, Ban công)')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon (Mã CSS hoặc Emoji)')),
            ],
            options={
                'verbose_name': 'Tiện nghi',
                'verbose_name_plural': '1. Quản lý Tiện nghi',
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại phòng')),
                ('slug', models.SlugField(help_text='Tạo URL tự động', unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('size', models.FloatField(help_text='VD: 45.5', verbose_name='Diện tích (m2)')),
                ('bed_type', models.CharField(help_text='VD: 1 Giường Đôi King', max_length=100, verbose_name='Loại giường')),
                ('capacity', models.IntegerField(default=2, verbose_name='Sức chứa (Người lớn)')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá phòng gốc (VND)')),
                ('promo_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá khuyến mãi (VND)')),
                ('amenities', models.ManyToManyField(blank=True, to='rooms.amenity', verbose_name='Tiện nghi đi kèm')),
            ],
            options={
                'verbose_name': 'Loại phòng',
                'verbose_name_plural': '2. Quản lý Loại phòng',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='Số phòng (VD: 101)')),
                ('status', models.CharField(choices=[('available', 'Phòng trống'), ('occupied', 'Đang có khách'), ('cleaning', 'Đang dọn dẹp'), ('maintenance', 'Bảo trì')], default='available', max_length=20, verbose_name='Trạng thái')),
                ('floor', models.IntegerField(verbose_name='Tầng')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomcategory', verbose_name='Thuộc loại phòng')),
            ],
            options={
                'verbose_name': 'Phòng thực tế',
                'verbose_name_plural': '3. Danh sách Phòng thực tế',
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/', verbose_name='Hình ảnh')),
                ('is_feature', models.BooleanField(default=False, verbose_name='Là ảnh đại diện chính')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.roomcategory')),
            ],
            options={
                'verbose_name': 'Hình ảnh',
                'verbose_name_plural': 'Hình ảnh Phòng',
            },
        ),
    ]
