# Generated by Django 6.1.1 on 2026-09-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='cancellation_policy',
            field=models.TextField(blank=True, default='', verbose_name='Chính sách hủy phòng'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Mô tả ngắn'),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='room_categories', to='rooms.amenity', verbose_name='Tiện nghi đi kèm'),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả chi tiết (HTML)'),
        ),
    ]
