# Generated by Django 6.1.1 on 2026-10-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomcategory_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả tiện nghi'),
        ),
    ]
