# Generated by Django 6.1.1 on 2026-10-10 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_promotion_name'),
        ('rooms', '0003_amenity_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã phiếu bảo trì')),
                ('equipment_name', models.CharField(max_length=150, verbose_name='Tên thiết bị hư hỏng')),
                ('issue_type', models.CharField(choices=[('electric', 'Hệ thống điện / Chiếu sáng'), ('ac', 'Điều hòa / Thông gió'), ('plumbing', 'Hệ thống nước / Thiết bị vệ sinh'), ('furniture', 'Nội thất / Bàn ghế / Khóa cửa'), ('electronics', 'Tivi / Tủ lạnh / Két sắt'), ('other', 'Khác')], default='ac', max_length=30, verbose_name='Phân loại sự cố')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả sự cố chi tiết')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tiếp nhận & Bắt đầu sửa')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn tất sửa chữa')),
                ('parts_replaced', models.CharField(blank=True, default='', max_length=255, verbose_name='Vật tư thay thế (VD: 1 Củ sen Inax, Tụ quạt 35uF)')),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Chi phí thay thế / sửa chữa (VND)')),
                ('is_guest_fault', models.BooleanField(default=False, verbose_name='Do khách làm hỏng (Khách bồi thường)?')),
                ('status', models.CharField(choices=[('fixing', 'Đang bảo trì / Sửa chữa'), ('completed', 'Đã sửa xong & Bàn giao dọn dẹp'), ('cancelled', 'Đã hủy phiếu')], default='fixing', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú hoàn tất')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='bookings.booking', verbose_name='Đơn đặt phòng bồi thường (nếu có)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Người lập phiếu')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='rooms.room', verbose_name='Phòng bảo trì')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Kỹ thuật viên thực hiện')),
            ],
            options={
                'verbose_name': 'Phiếu Bảo Trì & Sửa Chữa',
                'verbose_name_plural': '4. Phiếu Bảo Trì Thiết Bị',
                'ordering': ['-start_date'],
            },
        ),
    ]
