# Generated by Django 6.1.1 on 2026-09-26 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã Đặt Phòng')),
                ('check_in_date', models.DateField(verbose_name='Ngày Check-in (Dự kiến)')),
                ('check_out_date', models.DateField(verbose_name='Ngày Check-out (Có thể gia hạn)')),
                ('actual_check_in', models.DateTimeField(blank=True, null=True, verbose_name='Giờ Check-in thực tế')),
                ('actual_check_out', models.DateTimeField(blank=True, null=True, verbose_name='Giờ Check-out thực tế')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền phòng (VND)')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ duyệt'), ('confirmed', 'Đã xác nhận'), ('checked_in', 'Đã Check-in'), ('checked_out', 'Đã Check-out'), ('cancelled', 'Đã Hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú của khách')),
                ('internal_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú nội bộ (Lễ tân)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo đơn')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='rooms.room', verbose_name='Phòng')),
            ],
            options={
                'verbose_name': 'Đơn Đặt Phòng',
                'verbose_name_plural': '1. Danh sách Đặt Phòng',
            },
        ),
        migrations.CreateModel(
            name='BookingExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, verbose_name='Tên dịch vụ / Phụ phí (VD: Giặt ủi, Mini Bar, Đền bù)')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn giá (VND)')),
                ('added_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian thêm')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_services', to='bookings.booking', verbose_name='Thuộc Đơn đặt phòng')),
            ],
            options={
                'verbose_name': 'Dịch vụ phát sinh',
                'verbose_name_plural': 'Dịch vụ phát sinh',
            },
        ),
    ]
