# Generated by Django 6.1.1 on 2026-09-26 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã giảm giá (VD: SUMMER2026)')),
                ('discount_type', models.CharField(choices=[('percentage', 'Giảm theo phần trăm (%)'), ('fixed', 'Giảm số tiền cố định (VND)')], default='percentage', max_length=20, verbose_name='Loại khuyến mãi')),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá trị giảm')),
                ('valid_from', models.DateTimeField(verbose_name='Bắt đầu áp dụng')),
                ('valid_to', models.DateTimeField(verbose_name='Kết thúc áp dụng')),
                ('usage_limit', models.IntegerField(default=100, verbose_name='Tổng số lượt sử dụng tối đa')),
                ('used_count', models.IntegerField(default=0, verbose_name='Số lượt đã dùng')),
                ('min_order_value', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá trị đơn tối thiểu (VND)')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Mức giảm tối đa (VND) - Dùng cho %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kích hoạt')),
            ],
            options={
                'verbose_name': 'Mã Khuyến Mãi',
                'verbose_name_plural': 'Quản lý Khuyến Mãi',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='applied_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.promotion', verbose_name='Mã KM áp dụng'),
        ),
    ]
