# Generated by Django 6.1.1 on 2026-09-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_promotion_booking_applied_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Mã Khuyến Mãi', 'verbose_name_plural': '2. Quản lý Khuyến Mãi'},
        ),
        migrations.AddField(
            model_name='booking',
            name='identity_card',
            field=models.CharField(default='', max_length=20, verbose_name='Số CCCD / Hộ chiếu'),
        ),
    ]
