# Generated by Django 6.1.1 on 2026-09-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_category_alter_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ duyệt'), ('confirmed', 'Đã xác nhận'), ('checked_in', 'Đã Check-in'), ('checked_out', 'Đã Check-out'), ('completed', 'Đã hoàn tất'), ('cancelled', 'Đã Hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
