# Generated by Django 6.1.1 on 2026-10-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ duyệt'), ('confirmed', 'Đã xác nhận'), ('paid', 'Đã thanh toán'), ('PAID', 'Đã thanh toán'), ('checked_in', 'Đã Check-in'), ('checked_out', 'Đã Check-out'), ('completed', 'Đã hoàn tất'), ('no_show', 'Khách không đến (No-show)'), ('cancelled', 'Đã Hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
