# Generated by Django 6.1.1 on 2026-10-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Tên chương trình khuyến mãi'),
        ),
    ]
