# Generated by Django 6.1.1 on 2026-10-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_promotion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_points_awarded',
            field=models.BooleanField(default=False, verbose_name='Đã cộng điểm tích lũy'),
        ),
        migrations.AddField(
            model_name='booking',
            name='membership_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giảm giá Hạng thành viên (VND)'),
        ),
    ]
