# Generated by Django 6.1.1 on 2026-09-26 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhóm dịch vụ')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon đại diện')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Nhóm Dịch vụ',
                'verbose_name_plural': '1. Nhóm Dịch vụ',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên dịch vụ')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn giá (VND)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Hình ảnh minh họa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang phục vụ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='Thuộc nhóm')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': '2. Danh sách Dịch vụ',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('request_time', models.DateTimeField(verbose_name='Thời gian khách cần phục vụ')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý (Mới)'), ('in_progress', 'Đang thực hiện'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú (VD: Ít đường, Không hành...)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Giờ đặt lệnh')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='bookings.booking', verbose_name='Thuộc Đơn đặt phòng')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceitem', verbose_name='Dịch vụ yêu cầu')),
            ],
            options={
                'verbose_name': 'Phiếu Yêu Cầu',
                'verbose_name_plural': '3. Yêu cầu Dịch vụ (Concierge)',
            },
        ),
    ]
