# Generated by Django 6.1.1 on 2026-09-30 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phiếu Yêu Cầu Dịch Vụ', 'verbose_name_plural': '3. Yêu cầu Dịch vụ (Concierge)'},
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả chi tiết'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Đường dẫn ảnh trực tuyến (URL)'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền (VND)'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Giờ cập nhật'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả nhóm dịch vụ'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Icon đại diện (Emoji hoặc Icon Class)'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Hình ảnh tải lên'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên dịch vụ / Món ăn'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian khách cần phục vụ'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='services.serviceitem', verbose_name='Dịch vụ yêu cầu'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý (Pending)'), ('in_progress', 'Đang thực hiện (In Progress)'), ('completed', 'Đã hoàn thành (Completed)'), ('cancelled', 'Đã hủy (Cancelled)')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
