# Generated by Django 6.1.1 on 2026-09-26 04:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Số điện thoại')),
                ('role', models.CharField(choices=[('admin', 'Admin Hệ thống'), ('owner', 'Chủ Khách sạn'), ('manager', 'Quản lý Khách sạn'), ('cashier', 'Thu ngân'), ('receptionist', 'Lễ tân'), ('housekeeper', 'Nhân viên Dọn dẹp'), ('service_staff', 'Nhân viên Phục vụ'), ('technician', 'Kỹ thuật viên'), ('guest', 'Khách hàng')], default='guest', max_length=20, verbose_name='Vai trò')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '1. Tài khoản Đăng nhập',
                'verbose_name_plural': '1. Tài khoản Đăng nhập',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=10, unique=True, verbose_name='Mã nhân viên')),
                ('department', models.CharField(max_length=50, verbose_name='Phòng ban trực thuộc')),
                ('shift', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ca làm việc (Sáng/Chiều/Đêm)')),
                ('base_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Mức lương cơ bản (VND)')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Ngày vào làm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': '3. Hồ sơ Nhân sự',
                'verbose_name_plural': '3. Hồ sơ Nhân sự',
            },
        ),
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='CCCD / Passport')),
                ('loyalty_points', models.IntegerField(default=0, verbose_name='Điểm tích lũy (TA Club)')),
                ('vip_tier', models.CharField(default='Silver', max_length=50, verbose_name='Hạng Thành viên')),
                ('preferences', models.TextField(blank=True, null=True, verbose_name='Ghi chú sở thích (Dị ứng, gối nệm...)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': '2. Hồ sơ Khách hàng',
                'verbose_name_plural': '2. Hồ sơ Khách hàng',
            },
        ),
    ]
