# Generated by Django 6.1.1 on 2026-09-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chức danh / Vị trí công tác'),
        ),
    ]
