# Generated by Django 6.1.1 on 2026-10-09 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employeeprofile_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Tạo mới'), ('UPDATE', 'Cập nhật'), ('DELETE', 'Xóa'), ('LOGIN', 'Đăng nhập'), ('LOGOUT', 'Đăng xuất'), ('EXPORT', 'Xuất dữ liệu'), ('OTHER', 'Khác')], db_index=True, max_length=20, verbose_name='Hành động')),
                ('module', models.CharField(choices=[('BOOKING', 'Đặt phòng'), ('INVOICE', 'Hóa đơn & Thu ngân'), ('USER', 'Nhân sự & Người dùng'), ('ROOM', 'Buồng phòng'), ('SERVICE', 'Dịch vụ'), ('PROMOTION', 'Khuyến mãi'), ('SYSTEM', 'Cài đặt Hệ thống')], db_index=True, max_length=30, verbose_name='Phân hệ / Module')),
                ('description', models.TextField(verbose_name='Chi tiết mô tả thao tác')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời gian ghi nhận')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': '4. Nhật ký thao tác hệ thống',
                'verbose_name_plural': '4. Nhật ký thao tác hệ thống',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', '-created_at'], name='users_audit_module_d0d48f_idx'), models.Index(fields=['action', '-created_at'], name='users_audit_action_c40010_idx')],
            },
        ),
    ]
