# Generated by Django 6.1.1 on 2026-10-10 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên hạng thẻ')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã định danh (VD: BRONZE, SILVER, GOLD, DIAMOND)')),
                ('min_points', models.PositiveIntegerField(default=0, verbose_name='Điểm tối thiểu để đạt hạng')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Phần trăm giảm giá (%)')),
                ('badge_color', models.CharField(default='from-amber-700 via-amber-800 to-amber-950', max_length=100, verbose_name='Class màu nền / Gradient (Tailwind CSS)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả đặc quyền')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Thứ tự ưu tiên / Cấp bậc')),
            ],
            options={
                'verbose_name': 'Hạng thành viên',
                'verbose_name_plural': 'Quản lý Hạng thành viên',
                'ordering': ['order', 'min_points'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Tổng điểm tích lũy'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.membershiptier', verbose_name='Hạng thành viên hiện tại'),
        ),
    ]
