# Generated by Django 6.1.1 on 2026-10-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Chủ đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày gửi')),
            ],
            options={
                'verbose_name': 'Liên hệ',
                'verbose_name_plural': 'Danh sách liên hệ',
                'ordering': ['-created_at'],
            },
        ),
    ]
