# Generated by Django 6.1.1 on 2026-10-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề bài viết')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Đường dẫn tĩnh (Slug)')),
                ('category', models.CharField(choices=[('du_lich', 'Du lịch'), ('am_thuc', 'Ẩm thực'), ('khuyen_mai', 'Khuyến mãi'), ('su_kien', 'Sự kiện'), ('khach_san', 'Khách sạn')], default='du_lich', max_length=50, verbose_name='Chuyên mục')),
                ('author', models.CharField(default='Ban Biên Tập', max_length=150, verbose_name='Tác giả biên soạn')),
                ('status', models.CharField(choices=[('published', 'Hiển thị'), ('draft', 'Bản nháp')], default='published', max_length=20, verbose_name='Trạng thái')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Ảnh bìa bài viết')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Tóm tắt nội dung')),
                ('content', models.TextField(verbose_name='Nội dung chi tiết (HTML)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Bài viết & Tin tức',
                'verbose_name_plural': 'Quản lý Tin tức & Bài viết',
                'ordering': ['-created_at'],
            },
        ),
    ]
