# Generated by Django 6.1.1 on 2026-10-02 04:16

import apps.posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.posts.models.upload_image_path, verbose_name='File ảnh')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tải lên')),
            ],
            options={
                'verbose_name': 'Ảnh tải lên trình soạn thảo',
                'verbose_name_plural': 'Quản lý Ảnh soạn thảo',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
