# Generated by Django 6.1.1 on 2026-10-01 02:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0006_alter_booking_status'),
        ('rooms', '0002_roomcategory_cancellation_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness_score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Điểm vệ sinh (1-5)')),
                ('service_score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Điểm dịch vụ (1-5)')),
                ('location_score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Điểm vị trí (1-5)')),
                ('value_score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Điểm giá trị (1-5)')),
                ('overall_rating', models.FloatField(default=5.0, verbose_name='Điểm trung bình')),
                ('comment', models.TextField(verbose_name='Nội dung đánh giá')),
                ('admin_reply', models.TextField(blank=True, null=True, verbose_name='Phản hồi của khách sạn')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Trạng thái hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi đánh giá')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking', verbose_name='Đơn đặt phòng')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rooms.roomcategory', verbose_name='Hạng phòng')),
            ],
            options={
                'verbose_name': 'Đánh giá & Phản hồi',
                'verbose_name_plural': 'Quản lý Đánh giá',
                'ordering': ['-created_at'],
            },
        ),
    ]
