# Generated by Django 6.1.1 on 2026-09-26 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã Hóa Đơn')),
                ('room_charge', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền phòng')),
                ('service_charge', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền dịch vụ phát sinh')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giảm giá / Voucher')),
                ('tax', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thuế VAT')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='TỔNG THANH TOÁN (VND)')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('refunded', 'Đã hoàn tiền'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Tiền mặt'), ('credit_card', 'Thẻ tín dụng / Ghi nợ'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('momo', 'Ví điện tử (Momo/ZaloPay)')], max_length=50, null=True, verbose_name='Phương thức thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày lập hóa đơn')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thanh toán thành công')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='bookings.booking', verbose_name='Đơn đặt phòng')),
            ],
            options={
                'verbose_name': 'Hóa Đơn Thanh Toán',
                'verbose_name_plural': 'Quản lý Hóa Đơn',
            },
        ),
    ]
