# Generated by Django 6.1.1 on 2026-10-06 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_status'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền thanh toán')),
                ('payment_method', models.CharField(default='TRANSFER', max_length=50, verbose_name='Phương thức thanh toán')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('COMPLETED', 'Đã hoàn tất'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã giao dịch')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian thanh toán')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking', verbose_name='Đơn đặt phòng')),
            ],
            options={
                'verbose_name': 'Thanh Toán',
                'verbose_name_plural': 'Danh sách Thanh Toán',
                'ordering': ['-created_at'],
            },
        ),
    ]
