# Generated by Django 6.1.1 on 2026-10-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_bin', models.CharField(default='970422', max_length=20, verbose_name='Mã BIN ngân hàng')),
                ('account_no', models.CharField(default='123456789', max_length=50, verbose_name='Số tài khoản')),
                ('account_name', models.CharField(default='KHACH SAN TA DA NANG', max_length=100, verbose_name='Tên chủ tài khoản')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật gần nhất')),
            ],
            options={
                'verbose_name': 'Cấu hình Thanh toán VietQR',
                'verbose_name_plural': 'Cấu hình Thanh toán VietQR',
            },
        ),
    ]
